import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';

/**
 * Acceptance tests for Question 3. Do NOT edit this file.
 * Run them with:  npm test
 */
describe('Wallet API - interceptors & exception filters', () => {
  let app: INestApplication;
  let http: ReturnType<typeof request>;

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication({ logger: false });
    configureApp(app);
    await app.init();
    http = request(app.getHttpServer());
  });

  afterEach(async () => {
    await app.close();
  });

  const isIsoDate = (value: unknown) =>
    typeof value === 'string' && !Number.isNaN(Date.parse(value)) && new Date(value).toISOString() === value;

  const expectErrorEnvelope = (res: request.Response, statusCode: number, code: string, path: string) => {
    expect(Object.keys(res.body).sort()).toEqual(['error', 'path', 'success', 'timestamp']);
    expect(res.body.success).toBe(false);
    expect(res.body.error.statusCode).toBe(statusCode);
    expect(res.body.error.code).toBe(code);
    expect(res.body.error).toHaveProperty('message');
    expect(res.body.path).toBe(path);
    expect(isIsoDate(res.body.timestamp)).toBe(true);
  };

  const balanceOf = async (id: string): Promise<number> =>
    (await http.get(`/wallets/${id}`).expect(200)).body.data.balance;

  describe('Task 1 - response envelope', () => {
    it('wraps successful responses in { success, data, timestamp }', async () => {
      const res = await http.get('/wallets').expect(200);
      expect(Object.keys(res.body).sort()).toEqual(['data', 'success', 'timestamp']);
      expect(res.body.success).toBe(true);
      expect(res.body.data).toHaveLength(3);
      expect(res.body.data[0]).toEqual({ id: 'W-1001', owner: 'Aline Uwimana', currency: 'USD', balance: 250 });
      expect(isIsoDate(res.body.timestamp)).toBe(true);
    });

    it('wraps single objects too', async () => {
      const res = await http.get('/wallets/W-1002').expect(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.owner).toBe('Eric Nshuti');
    });

    it('does NOT wrap routes marked with @RawResponse() (GET /health)', async () => {
      const res = await http.get('/health').expect(200);
      expect(res.body).toEqual({ status: 'ok' });
    });
  });

  describe('Task 2 - global exception filter', () => {
    it('formats framework errors (unknown route -> 404 NOT_FOUND)', async () => {
      const res = await http.get('/does-not-exist').expect(404);
      expectErrorEnvelope(res, 404, 'NOT_FOUND', '/does-not-exist');
    });

    it('keeps the list of validation messages (400 BAD_REQUEST)', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-1002', amount: -5 }).expect(400);
      expectErrorEnvelope(res, 400, 'BAD_REQUEST', '/transfers');
      expect(Array.isArray(res.body.error.message)).toBe(true);
      expect(res.body.error.message.join(' ')).toContain('amount');
    });

    it.each([[0.001], ['10'], [0]])('rejects invalid amount %p with 400', async (amount) => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-1002', amount }).expect(400);
      expect(res.body.error.code).toBe('BAD_REQUEST');
    });

    it('hides unexpected errors behind a generic 500', async () => {
      const res = await http.get('/debug/crash').expect(500);
      expectErrorEnvelope(res, 500, 'INTERNAL_SERVER_ERROR', '/debug/crash');
      expect(res.body.error.message).toBe('Internal server error');
      expect(res.text).not.toContain('hunter2');
      expect(res.text).not.toContain('wallet_admin');
    });
  });

  describe('Task 3 - X-Response-Time header', () => {
    it('adds X-Response-Time to successful responses', async () => {
      const res = await http.get('/wallets').expect(200);
      expect(res.headers['x-response-time']).toMatch(/^\d+ms$/);
    });

    it('adds it to POST responses as well', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1003', toWalletId: 'W-1001', amount: 10 }).expect(201);
      expect(res.headers['x-response-time']).toMatch(/^\d+ms$/);
    });
  });

  describe('Task 4 - custom domain exceptions', () => {
    it('unknown wallet -> 404 WALLET_NOT_FOUND', async () => {
      const res = await http.get('/wallets/W-9999').expect(404);
      expectErrorEnvelope(res, 404, 'WALLET_NOT_FOUND', '/wallets/W-9999');
      expect(res.body.error.message).toBe('Wallet W-9999 not found');
    });

    it('same source and destination -> 400 SAME_WALLET_TRANSFER', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-1001', amount: 5 }).expect(400);
      expectErrorEnvelope(res, 400, 'SAME_WALLET_TRANSFER', '/transfers');
    });

    it('not enough money -> 422 INSUFFICIENT_FUNDS', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1002', toWalletId: 'W-1001', amount: 40.51 }).expect(422);
      expectErrorEnvelope(res, 422, 'INSUFFICIENT_FUNDS', '/transfers');
      expect(res.body.error.message.toLowerCase()).toContain('insufficient funds');
    });
  });

  describe('Task 5 - correct transfers', () => {
    it('moves money and returns the transfer (201)', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-1002', amount: 50 }).expect(201);
      expect(res.body.success).toBe(true);
      expect(res.body.data).toMatchObject({ id: 'T-0001', fromWalletId: 'W-1001', toWalletId: 'W-1002', amount: 50 });
      expect(isIsoDate(res.body.data.createdAt)).toBe(true);

      expect(await balanceOf('W-1001')).toBe(200);
      expect(await balanceOf('W-1002')).toBe(90.5);

      const list = await http.get('/transfers').expect(200);
      expect(list.body.data).toHaveLength(1);
    });

    it('allows spending the exact balance', async () => {
      await http.post('/transfers').send({ fromWalletId: 'W-1002', toWalletId: 'W-1001', amount: 40.5 }).expect(201);
      expect(await balanceOf('W-1002')).toBe(0);
    });

    it('does not change any balance when funds are insufficient', async () => {
      await http.post('/transfers').send({ fromWalletId: 'W-1002', toWalletId: 'W-1001', amount: 100 }).expect(422);
      expect(await balanceOf('W-1002')).toBe(40.5);
      expect(await balanceOf('W-1001')).toBe(250);
    });

    it('does not debit the sender when the receiver does not exist', async () => {
      const res = await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-9999', amount: 10 }).expect(404);
      expect(res.body.error.code).toBe('WALLET_NOT_FOUND');
      expect(await balanceOf('W-1001')).toBe(250);
      const list = await http.get('/transfers').expect(200);
      expect(list.body.data).toHaveLength(0);
    });

    it('keeps balances exact to the cent (no floating point drift)', async () => {
      for (let i = 0; i < 3; i++) {
        await http.post('/transfers').send({ fromWalletId: 'W-1001', toWalletId: 'W-1002', amount: 0.1 }).expect(201);
      }
      expect(await balanceOf('W-1001')).toBe(249.7);
      expect(await balanceOf('W-1002')).toBe(40.8);
    });
  });
});
