import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';
import { APP_CONFIG, CLOCK, Clock, SLUG_GENERATOR, SlugGenerator } from '../src/links/links.constants';

/**
 * Acceptance tests for Question 4. Do NOT edit this file.
 * Run them with:  npm test
 *
 * The real slug generator, clock and config are replaced with fakes so the
 * results are predictable. This only works if your code gets them through
 * dependency injection using the tokens in links.constants.ts.
 */
class FakeSlugGenerator implements SlugGenerator {
  queue: string[] = [];
  generate(): string {
    const next = this.queue.shift();
    if (!next) throw new Error('FakeSlugGenerator: no more slugs queued');
    return next;
  }
}

class FakeClock implements Clock {
  current = new Date('2026-01-01T10:00:00.000Z');
  now(): Date {
    return new Date(this.current);
  }
  advanceMinutes(minutes: number) {
    this.current = new Date(this.current.getTime() + minutes * 60_000);
  }
}

describe('URL Shortener - providers, pipes, middleware & redirects', () => {
  let app: INestApplication;
  let http: ReturnType<typeof request>;
  let slugs: FakeSlugGenerator;
  let clock: FakeClock;

  const T0 = '2026-01-01T10:00:00.000Z';
  const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

  beforeEach(async () => {
    slugs = new FakeSlugGenerator();
    clock = new FakeClock();
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] })
      .overrideProvider(SLUG_GENERATOR)
      .useValue(slugs)
      .overrideProvider(CLOCK)
      .useValue(clock)
      .overrideProvider(APP_CONFIG)
      .useValue({ baseUrl: 'https://sho.rt' })
      .compile();
    app = moduleRef.createNestApplication({ logger: false });
    configureApp(app);
    await app.init();
    http = request(app.getHttpServer());
  });

  afterEach(async () => {
    await app.close();
  });

  describe('Task 1 - validation', () => {
    it.each([['not-a-url'], ['nestjs.com'], ['ftp://files.example.com/a.zip'], ['']])(
      'rejects url %p (400)',
      async (url) => {
        await http.post('/links').send({ url }).expect(400);
      },
    );

    it.each([['abc'], ['has space'], ['under_score'], ['x'.repeat(21)]])(
      'rejects customSlug %p (400)',
      async (customSlug) => {
        await http.post('/links').send({ url: 'https://nestjs.com', customSlug }).expect(400);
      },
    );

    it.each([[0], [-5], [1.5], ['10'], [525601]])('rejects expiresInMinutes %p (400)', async (expiresInMinutes) => {
      await http.post('/links').send({ url: 'https://nestjs.com', expiresInMinutes }).expect(400);
    });
  });

  describe('Task 2 - creating links with injected providers', () => {
    it('uses the injected slug generator, clock and base URL', async () => {
      slugs.queue.push('abc123');
      const res = await http.post('/links').send({ url: 'https://docs.nestjs.com/providers' }).expect(201);
      expect(res.body).toMatchObject({
        slug: 'abc123',
        url: 'https://docs.nestjs.com/providers',
        shortUrl: 'https://sho.rt/abc123',
        clicks: 0,
        createdAt: T0,
        expiresAt: null,
      });
    });

    it('uses customSlug when provided (and does not call the generator)', async () => {
      const res = await http.post('/links').send({ url: 'https://nestjs.com', customSlug: 'nest-home' }).expect(201);
      expect(res.body.slug).toBe('nest-home');
      expect(res.body.shortUrl).toBe('https://sho.rt/nest-home');
    });

    it('rejects a customSlug that is already taken (409)', async () => {
      await http.post('/links').send({ url: 'https://nestjs.com', customSlug: 'nest-home' }).expect(201);
      await http.post('/links').send({ url: 'https://example.com', customSlug: 'nest-home' }).expect(409);
    });

    it('computes expiresAt from the injected clock', async () => {
      slugs.queue.push('exp001');
      const res = await http.post('/links').send({ url: 'https://nestjs.com', expiresInMinutes: 90 }).expect(201);
      expect(res.body.expiresAt).toBe('2026-01-01T11:30:00.000Z');
    });

    it('retries when the generated slug collides with an existing one', async () => {
      slugs.queue.push('abc123');
      await http.post('/links').send({ url: 'https://a.example.com' }).expect(201);

      slugs.queue.push('abc123', 'abc123', 'xyz789');
      const res = await http.post('/links').send({ url: 'https://b.example.com' }).expect(201);
      expect(res.body.slug).toBe('xyz789');
    });

    it('gives up with 503 after 5 colliding attempts', async () => {
      slugs.queue.push('abc123');
      await http.post('/links').send({ url: 'https://a.example.com' }).expect(201);

      slugs.queue.push(...Array(10).fill('abc123'));
      await http.post('/links').send({ url: 'https://b.example.com' }).expect(503);
      expect(slugs.queue).toHaveLength(5); // exactly 5 attempts were made
    });
  });

  describe('Task 3 - redirect + SlugPipe', () => {
    it('redirects GET /:slug to the original URL with 302', async () => {
      slugs.queue.push('abc123');
      await http.post('/links').send({ url: 'https://docs.nestjs.com/pipes' }).expect(201);
      const res = await http.get('/abc123').expect(302);
      expect(res.headers.location).toBe('https://docs.nestjs.com/pipes');
    });

    it('returns 404 for an unknown slug', async () => {
      await http.get('/nothing-here').expect(404);
    });

    it.each([['/ab'], ['/under_score'], ['/' + 'x'.repeat(21)]])(
      'returns 400 for a malformed slug %s (SlugPipe)',
      async (path) => {
        await http.get(path).expect(400);
      },
    );

    it('returns 410 Gone once the link has expired', async () => {
      slugs.queue.push('exp001');
      await http.post('/links').send({ url: 'https://nestjs.com', expiresInMinutes: 10 }).expect(201);

      clock.advanceMinutes(9);
      await http.get('/exp001').expect(302);

      clock.advanceMinutes(1); // exactly at expiresAt -> expired
      await http.get('/exp001').expect(410);
    });
  });

  describe('Task 4 - stats', () => {
    it('counts clicks and records the last access time', async () => {
      slugs.queue.push('abc123');
      await http.post('/links').send({ url: 'https://nestjs.com' }).expect(201);

      await http.get('/abc123').expect(302);
      clock.advanceMinutes(5);
      await http.get('/abc123').expect(302);

      const res = await http.get('/links/abc123/stats').expect(200);
      expect(res.body).toMatchObject({
        slug: 'abc123',
        url: 'https://nestjs.com',
        shortUrl: 'https://sho.rt/abc123',
        clicks: 2,
        createdAt: T0,
        expiresAt: null,
        lastAccessedAt: '2026-01-01T10:05:00.000Z',
        expired: false,
      });
    });

    it('does not count blocked visits to an expired link', async () => {
      slugs.queue.push('exp001');
      await http.post('/links').send({ url: 'https://nestjs.com', expiresInMinutes: 1 }).expect(201);
      clock.advanceMinutes(2);
      await http.get('/exp001').expect(410);

      const res = await http.get('/links/exp001/stats').expect(200);
      expect(res.body).toMatchObject({ clicks: 0, lastAccessedAt: null, expired: true });
    });

    it('returns 404 for unknown slugs and 400 for malformed ones', async () => {
      await http.get('/links/nothing-here/stats').expect(404);
      await http.get('/links/ab/stats').expect(400);
    });
  });

  describe('Task 5 - RequestIdMiddleware', () => {
    it('generates a UUID v4 X-Request-Id when the client sends none', async () => {
      const r1 = await http.get('/links/nothing-here/stats').expect(404);
      const r2 = await http.get('/links/nothing-here/stats').expect(404);
      expect(r1.headers['x-request-id']).toMatch(UUID_V4);
      expect(r2.headers['x-request-id']).toMatch(UUID_V4);
      expect(r1.headers['x-request-id']).not.toBe(r2.headers['x-request-id']);
    });

    it('echoes the X-Request-Id sent by the client', async () => {
      slugs.queue.push('abc123');
      const res = await http
        .post('/links')
        .set('X-Request-Id', 'trace-42')
        .send({ url: 'https://nestjs.com' })
        .expect(201);
      expect(res.headers['x-request-id']).toBe('trace-42');
    });

    it('also applies to redirects', async () => {
      slugs.queue.push('abc123');
      await http.post('/links').send({ url: 'https://nestjs.com' }).expect(201);
      const res = await http.get('/abc123').expect(302);
      expect(res.headers['x-request-id']).toMatch(UUID_V4);
    });
  });
});
