import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';

/**
 * Acceptance tests for Question 1. Do NOT edit this file.
 * Run them with:  npm test
 */
describe('Library Books API', () => {
  let app: INestApplication;
  let http: ReturnType<typeof request>;

  const validBook = {
    title: 'The Mythical Man-Month',
    author: 'Frederick P. Brooks Jr.',
    isbn: '9780201835953',
    publishedYear: 1995,
  };

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    configureApp(app);
    await app.init();
    http = request(app.getHttpServer());
  });

  afterEach(async () => {
    await app.close();
  });

  const messagesOf = (res: request.Response): string =>
    JSON.stringify(res.body?.message ?? '').toLowerCase();

  describe('Task 2 - POST /books', () => {
    it('creates a book (201), assigns the next id and applies defaults', async () => {
      const res = await http.post('/books').send(validBook).expect(201);
      expect(res.body).toEqual({
        id: 13,
        ...validBook,
        genres: [],
        available: true,
      });
    });

    it('keeps provided genres and available flag', async () => {
      const res = await http
        .post('/books')
        .send({ ...validBook, genres: ['programming', 'management'], available: false })
        .expect(201);
      expect(res.body.genres).toEqual(['programming', 'management']);
      expect(res.body.available).toBe(false);
    });

    it('makes the new book retrievable', async () => {
      await http.post('/books').send(validBook).expect(201);
      const res = await http.get('/books/13').expect(200);
      expect(res.body.title).toBe(validBook.title);
    });

    it('rejects a missing or empty title (400)', async () => {
      const { title, ...noTitle } = validBook;
      const r1 = await http.post('/books').send(noTitle).expect(400);
      expect(messagesOf(r1)).toContain('title');
      const r2 = await http.post('/books').send({ ...validBook, title: '   ' }).expect(400);
      expect(messagesOf(r2)).toContain('title');
    });

    it('rejects a title longer than 200 characters (400)', async () => {
      await http.post('/books').send({ ...validBook, title: 'x'.repeat(201) }).expect(400);
    });

    it('rejects a missing author (400)', async () => {
      const { author, ...noAuthor } = validBook;
      const res = await http.post('/books').send(noAuthor).expect(400);
      expect(messagesOf(res)).toContain('author');
    });

    it.each([['12345'], ['9780201835953X'], ['1234567890123'], ['97802018359']])(
      'rejects invalid isbn "%s" (400)',
      async (isbn) => {
        const res = await http.post('/books').send({ ...validBook, isbn }).expect(400);
        expect(messagesOf(res)).toContain('isbn');
      },
    );

    it.each([[1449], [new Date().getFullYear() + 1], [2001.5], ['1995']])(
      'rejects invalid publishedYear %p (400)',
      async (publishedYear) => {
        const res = await http.post('/books').send({ ...validBook, publishedYear }).expect(400);
        expect(messagesOf(res)).toContain('publishedyear');
      },
    );

    it('rejects invalid genres (400)', async () => {
      await http.post('/books').send({ ...validBook, genres: 'fiction' }).expect(400);
      await http.post('/books').send({ ...validBook, genres: ['fiction', ''] }).expect(400);
      await http.post('/books').send({ ...validBook, genres: ['a', 'b', 'c', 'd', 'e', 'f'] }).expect(400);
    });

    it('rejects a non-boolean available (400)', async () => {
      await http.post('/books').send({ ...validBook, available: 'yes' }).expect(400);
    });

    it('rejects unknown properties (400)', async () => {
      const res = await http.post('/books').send({ ...validBook, id: 99, price: 10 }).expect(400);
      expect(messagesOf(res)).toContain('price');
    });

    it('rejects a duplicate ISBN with 409 Conflict', async () => {
      const res = await http
        .post('/books')
        .send({ ...validBook, isbn: '9780132350884' })
        .expect(409);
      expect(messagesOf(res)).toContain('9780132350884');
    });
  });

  describe('Task 3 - GET /books (filters + pagination)', () => {
    it('returns the first page with default pagination', async () => {
      const res = await http.get('/books').expect(200);
      expect(res.body.data).toHaveLength(10);
      expect(res.body.data[0].id).toBe(1);
      expect(res.body.meta).toEqual({ total: 12, page: 1, limit: 10, totalPages: 2 });
    });

    it('paginates with page & limit', async () => {
      const res = await http.get('/books?page=3&limit=5').expect(200);
      expect(res.body.data.map((b: any) => b.id)).toEqual([11, 12]);
      expect(res.body.meta).toEqual({ total: 12, page: 3, limit: 5, totalPages: 3 });
    });

    it('returns an empty page past the end', async () => {
      const res = await http.get('/books?page=9').expect(200);
      expect(res.body.data).toEqual([]);
      expect(res.body.meta.total).toBe(12);
    });

    it('filters by author (case-insensitive, partial match)', async () => {
      const res = await http.get('/books?author=MARTIN').expect(200);
      expect(res.body.data.map((b: any) => b.id)).toEqual([4, 5, 6, 11]);
      expect(res.body.meta.total).toBe(4);
    });

    it('filters by genre (case-insensitive) combined with available=true', async () => {
      const res = await http.get('/books?genre=Programming&available=true').expect(200);
      expect(res.body.data.map((b: any) => b.id)).toEqual([4, 5, 9]);
    });

    it('treats available=false as the boolean false', async () => {
      const res = await http.get('/books?available=false').expect(200);
      expect(res.body.data.map((b: any) => b.id)).toEqual([3, 6, 11]);
      expect(res.body.data.every((b: any) => b.available === false)).toBe(true);
    });

    it('applies pagination after filtering', async () => {
      const res = await http.get('/books?genre=programming&limit=2&page=2').expect(200);
      expect(res.body.data.map((b: any) => b.id)).toEqual([6, 9]);
      expect(res.body.meta).toEqual({ total: 5, page: 2, limit: 2, totalPages: 3 });
    });

    it.each([['page=0'], ['page=abc'], ['limit=0'], ['limit=51'], ['page=1.5'], ['available=maybe']])(
      'rejects invalid query "%s" (400)',
      async (qs) => {
        await http.get(`/books?${qs}`).expect(400);
      },
    );
  });

  describe('Task 4 - GET /books/:id', () => {
    it('returns a single book', async () => {
      const res = await http.get('/books/4').expect(200);
      expect(res.body).toMatchObject({ id: 4, title: 'Clean Code' });
    });

    it('returns 400 when the id is not an integer', async () => {
      await http.get('/books/abc').expect(400);
    });

    it('returns 404 with a helpful message when the book does not exist', async () => {
      const res = await http.get('/books/999').expect(404);
      expect(res.body.message).toBe('Book with id 999 not found');
    });
  });

  describe('Task 5 - PATCH /books/:id', () => {
    it('updates only the provided fields', async () => {
      const res = await http.patch('/books/1').send({ available: false, genres: ['classic'] }).expect(200);
      expect(res.body).toEqual({
        id: 1,
        title: 'Things Fall Apart',
        author: 'Chinua Achebe',
        isbn: '9780385474542',
        publishedYear: 1958,
        genres: ['classic'],
        available: false,
      });
      const after = await http.get('/books/1').expect(200);
      expect(after.body.available).toBe(false);
    });

    it('allows keeping the same ISBN', async () => {
      await http.patch('/books/1').send({ isbn: '9780385474542' }).expect(200);
    });

    it('validates the fields that are provided (400)', async () => {
      await http.patch('/books/1').send({ publishedYear: 'last year' }).expect(400);
      await http.patch('/books/1').send({ title: '' }).expect(400);
      await http.patch('/books/1').send({ id: 50 }).expect(400);
    });

    it('returns 404 for an unknown book', async () => {
      await http.patch('/books/999').send({ title: 'Ghost' }).expect(404);
    });

    it("returns 409 when changing the ISBN to another book's ISBN", async () => {
      await http.patch('/books/1').send({ isbn: '9780132350884' }).expect(409);
    });
  });

  describe('Task 6 - DELETE /books/:id', () => {
    it('deletes a book and returns 204 with no body', async () => {
      const res = await http.delete('/books/2').expect(204);
      expect(res.text).toBe('');
      await http.get('/books/2').expect(404);
      const list = await http.get('/books').expect(200);
      expect(list.body.meta.total).toBe(11);
    });

    it('returns 404 for an unknown book', async () => {
      await http.delete('/books/999').expect(404);
    });
  });
});
