import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';

/**
 * Acceptance tests for Question 2. Do NOT edit this file.
 * Run them with:  npm test
 */
const AMINA = 'Bearer token-amina'; // admin
const BRIAN = 'Bearer token-brian'; // member, owns tasks 1 & 2
const CHLOE = 'Bearer token-chloe'; // member, owns tasks 3 & 4
const DIEGO = 'Bearer token-diego'; // viewer

describe('Team Tasks API - authentication & authorization', () => {
  let app: INestApplication;
  let http: ReturnType<typeof request>;

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    configureApp(app);
    await app.init();
    http = request(app.getHttpServer());
  });

  afterEach(async () => {
    await app.close();
  });

  describe('Task 1 - AuthGuard (401)', () => {
    it('rejects a request without an Authorization header', async () => {
      const res = await http.get('/tasks').expect(401);
      expect(res.body.message).toBe('Missing or invalid access token');
    });

    it('rejects an unknown token', async () => {
      await http.get('/tasks').set('Authorization', 'Bearer token-nobody').expect(401);
    });

    it.each([['token-brian'], ['Basic token-brian'], ['Bearer'], ['Bearer   ']])(
      'rejects a malformed header "%s"',
      async (header) => {
        await http.get('/tasks').set('Authorization', header).expect(401);
      },
    );

    it('accepts a valid token', async () => {
      await http.get('/tasks').set('Authorization', BRIAN).expect(200);
    });

    it('is secure by default: an undecorated controller also requires a token', async () => {
      await http.get('/projects').expect(401);
      await http.get('/projects').set('Authorization', DIEGO).expect(200);
    });
  });

  describe('Task 2 - @Public()', () => {
    it('lets anyone call GET /health', async () => {
      const res = await http.get('/health').expect(200);
      expect(res.body).toEqual({ status: 'ok' });
    });

    it('lets anyone call GET /', async () => {
      await http.get('/').expect(200);
    });
  });

  describe('Task 3 - @Roles() + RolesGuard (403)', () => {
    it('GET /users is admin-only', async () => {
      await http.get('/users').set('Authorization', AMINA).expect(200);
      await http.get('/users').set('Authorization', BRIAN).expect(403);
      await http.get('/users').set('Authorization', DIEGO).expect(403);
    });

    it('lets every role read tasks', async () => {
      for (const who of [AMINA, BRIAN, DIEGO]) {
        const res = await http.get('/tasks').set('Authorization', who).expect(200);
        expect(res.body).toHaveLength(4);
      }
      await http.get('/tasks/3').set('Authorization', DIEGO).expect(200);
    });

    it('only admins and members can create tasks', async () => {
      await http.post('/tasks').set('Authorization', DIEGO).send({ title: 'Nope' }).expect(403);
      await http.post('/tasks').set('Authorization', AMINA).send({ title: 'Plan sprint' }).expect(201);
    });

    it('only admins can delete tasks', async () => {
      await http.delete('/tasks/1').set('Authorization', BRIAN).expect(403);
      await http.delete('/tasks/1').set('Authorization', AMINA).expect(204);
      await http.get('/tasks/1').set('Authorization', AMINA).expect(404);
    });

    it('viewers cannot update tasks', async () => {
      await http.patch('/tasks/1').set('Authorization', DIEGO).send({ status: 'todo' }).expect(403);
    });
  });

  describe('Task 4 - @CurrentUser() & ownership', () => {
    it('GET /users/me returns the caller (overrides the admin-only class rule)', async () => {
      const brian = await http.get('/users/me').set('Authorization', BRIAN).expect(200);
      expect(brian.body).toEqual({ id: 2, name: 'Brian Mugisha', email: 'brian@example.com', role: 'member' });

      const diego = await http.get('/users/me').set('Authorization', DIEGO).expect(200);
      expect(diego.body.id).toBe(4);
    });

    it('GET /users/me still requires a token', async () => {
      await http.get('/users/me').expect(401);
    });

    it('sets the owner of a new task to the caller and ignores ownerId in the body', async () => {
      const res = await http
        .post('/tasks')
        .set('Authorization', BRIAN)
        .send({ title: 'Review PR #42', ownerId: 3 })
        .expect(201);
      expect(res.body).toMatchObject({ id: 5, title: 'Review PR #42', status: 'todo', ownerId: 2 });
    });

    it('members can update their own tasks', async () => {
      const res = await http.patch('/tasks/2').set('Authorization', BRIAN).send({ status: 'done' }).expect(200);
      expect(res.body.status).toBe('done');
    });

    it("members cannot update someone else's task", async () => {
      const res = await http.patch('/tasks/3').set('Authorization', BRIAN).send({ status: 'done' }).expect(403);
      expect(res.body.message).toBe('You can only modify your own tasks');
      const task = await http.get('/tasks/3').set('Authorization', CHLOE).expect(200);
      expect(task.body.status).toBe('todo');
    });

    it('admins can update any task', async () => {
      await http.patch('/tasks/3').set('Authorization', AMINA).send({ title: 'Redesign onboarding' }).expect(200);
    });

    it('members cannot steal a task by changing its ownerId', async () => {
      const res = await http.patch('/tasks/1').set('Authorization', BRIAN).send({ ownerId: 3 }).expect(200);
      expect(res.body.ownerId).toBe(2);
    });

    it('returns 404 for an unknown task', async () => {
      await http.patch('/tasks/999').set('Authorization', AMINA).send({ status: 'done' }).expect(404);
    });
  });

  describe('Task 5 - never leak tokens', () => {
    it('GET /users does not expose any token', async () => {
      const res = await http.get('/users').set('Authorization', AMINA).expect(200);
      expect(res.body).toHaveLength(4);
      for (const user of res.body) {
        expect(user).not.toHaveProperty('token');
      }
      expect(JSON.stringify(res.body)).not.toContain('token-');
    });

    it('GET /users/me does not expose the token', async () => {
      const res = await http.get('/users/me').set('Authorization', AMINA).expect(200);
      expect(res.body).not.toHaveProperty('token');
    });
  });
});
