import { Book } from './book.entity';

// Seed data. The tests rely on these exact 12 books, so do not edit this file.
export const SEED_BOOKS: Book[] = [
  { id: 1, title: 'Things Fall Apart', author: 'Chinua Achebe', isbn: '9780385474542', publishedYear: 1958, genres: ['fiction', 'classic'], available: true },
  { id: 2, title: 'Half of a Yellow Sun', author: 'Chimamanda Ngozi Adichie', isbn: '9781400095209', publishedYear: 2006, genres: ['fiction', 'historical'], available: true },
  { id: 3, title: 'Americanah', author: 'Chimamanda Ngozi Adichie', isbn: '9780307455925', publishedYear: 2013, genres: ['fiction', 'romance'], available: false },
  { id: 4, title: 'Clean Code', author: 'Robert C. Martin', isbn: '9780132350884', publishedYear: 2008, genres: ['programming', 'software-engineering'], available: true },
  { id: 5, title: 'The Clean Coder', author: 'Robert C. Martin', isbn: '9780137081073', publishedYear: 2011, genres: ['programming', 'career'], available: true },
  { id: 6, title: 'Refactoring', author: 'Martin Fowler', isbn: '9780134757599', publishedYear: 2018, genres: ['programming', 'software-engineering'], available: false },
  { id: 7, title: 'Sapiens', author: 'Yuval Noah Harari', isbn: '9780062316097', publishedYear: 2011, genres: ['history', 'non-fiction'], available: true },
  { id: 8, title: 'Long Walk to Freedom', author: 'Nelson Mandela', isbn: '9780316548182', publishedYear: 1994, genres: ['biography', 'history'], available: true },
  { id: 9, title: 'The Pragmatic Programmer', author: 'Andrew Hunt', isbn: '9780135957059', publishedYear: 2019, genres: ['programming', 'career'], available: true },
  { id: 10, title: 'Purple Hibiscus', author: 'Chimamanda Ngozi Adichie', isbn: '9781616202415', publishedYear: 2003, genres: ['fiction'], available: true },
  { id: 11, title: 'Designing Data-Intensive Applications', author: 'Martin Kleppmann', isbn: '9781449373320', publishedYear: 2017, genres: ['programming', 'databases'], available: false },
  { id: 12, title: 'Educated', author: 'Tara Westover', isbn: '9780399590504', publishedYear: 2018, genres: ['biography', 'non-fiction'], available: true },
];
